-- Historic_Moment
-- Author: gu186
-- DateCreated: 12/24/2022 8:21:59 AM
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS MomentIllustrations (MomentIllustrationType TEXT, MomentDataType TEXT, GameDataType TEXT, Texture TEXT);
INSERT INTO MomentIllustrations
        (MomentIllustrationType,               MomentDataType,        GameDataType,                        Texture)
VALUES  ('MOMENT_ILLUSTRATION_UNIQUE_UNIT',    'MOMENT_DATA_UNIT',    'UNIT_SHI_WEI',          'ICON_UNIT_SHI_WEI_PORTRAIT_MOMENT.dds'),
		('MOMENT_ILLUSTRATION_UNIQUE_UNIT',    'MOMENT_DATA_UNIT',    'UNIT_LI_LIJUN',          'ICON_UNIT_LI_LIJUN_PORTRAIT_MOMENT.dds'),
		('MOMENT_ILLUSTRATION_UNIQUE_UNIT',    'MOMENT_DATA_UNIT',    'UNIT_LI_JIAN',          'ICON_UNIT_LI_JIAN_PORTRAIT_MOMENT.dds'),
		('MOMENT_ILLUSTRATION_UNIQUE_UNIT',    'MOMENT_DATA_UNIT',    'UNIT_FEN_CHEN',          'ICON_UNIT_FEN_CHEN_PORTRAIT_MOMENT.dds'),
		('MOMENT_ILLUSTRATION_UNIQUE_DISTRICT',    'MOMENT_DATA_DISTRICT',    'DISTRICT_TEACHING_BUILDING',          'ICON_DISTRICT_TEACHING_BUILDING_MOMENT.dds'),
		('MOMENT_ILLUSTRATION_UNIQUE_DISTRICT',    'MOMENT_DATA_DISTRICT',    'DISTRICT_LECTURE_HALL',          'ICON_DISTRICT_LECTURE_HALL_MOMENT.dds'),
        ('MOMENT_ILLUSTRATION_UNIQUE_IMPROVEMENT',    'MOMENT_DATA_IMPROVEMENT',    'IMPROVEMENT_HONEST_SHOP',     'ICON_IMPROVEMENT_HONEST_SHOP_MOMENT.dds');